# Run docker-compose build
# Run docker-compose up -d

version: '3.1'

services:

  backend:
    image: node:10-alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Europe/Amsterdam
      - TZ=Europe/Amsterdam
